//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStudio.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppStudio.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About
        {
            get
            {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText
        {
            get
            {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText
        {
            get
            {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle
        {
            get
            {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error sharing.
        /// </summary>
        public static string Error
        {
            get
            {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to go to source.
        /// </summary>
        public static string GoToSource
        {
            get
            {
                return ResourceManager.GetString("GoToSource", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to http://apps.windowsstore.com/.
        /// </summary>
        public static string HomeUrl
        {
            get
            {
                return ResourceManager.GetString("HomeUrl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to lock screen.
        /// </summary>
        public static string LockScreen
        {
            get
            {
                return ResourceManager.GetString("LockScreen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to pin to start.
        /// </summary>
        public static string PinToStart
        {
            get
            {
                return ResourceManager.GetString("PinToStart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string Refresh
        {
            get
            {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection
        {
            get
            {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage
        {
            get
            {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share
        {
            get
            {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to share app.
        /// </summary>
        public static string ShareApp
        {
            get
            {
                return ResourceManager.GetString("ShareApp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Share by email.
        /// </summary>
        public static string ShareByEmail
        {
            get
            {
                return ResourceManager.GetString("ShareByEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Share image.
        /// </summary>
        public static string ShareImage
        {
            get
            {
                return ResourceManager.GetString("ShareImage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string ShareItem
        {
            get
            {
                return ResourceManager.GetString("ShareItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Share link.
        /// </summary>
        public static string ShareLink
        {
            get
            {
                return ResourceManager.GetString("ShareLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to choose a sharing option.
        /// </summary>
        public static string ShareMessage
        {
            get
            {
                return ResourceManager.GetString("ShareMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Share status.
        /// </summary>
        public static string ShareStatus
        {
            get
            {
                return ResourceManager.GetString("ShareStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to read.
        /// </summary>
        public static string SpeakText
        {
            get
            {
                return ResourceManager.GetString("SpeakText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tap+Send.
        /// </summary>
        public static string TapSend
        {
            get
            {
                return ResourceManager.GetString("TapSend", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Go ahead and tap your phone against another device..
        /// </summary>
        public static string TapSendMessage
        {
            get
            {
                return ResourceManager.GetString("TapSendMessage", resourceCulture);
            }
        }
    }
}
