name: Build .NET App

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-2019
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0

    - name: Restore NuGet packages
      run: nuget restore App.sln

    - name: Build solution
      run: msbuild App.sln /t:Build:Rebuild /p:Configuration=Release /p:DeployOnBuild=true

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: armia-polcyn-app
        path: Aptor\obj\Release\Package
